### ISSUE TITLE
Publish to both `master` as well as `latest` branch, so that `master` verbiage can be removed from the repository

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisoriesBuilder#141]
As per current zeitgeist and understandable rationale, `master` verbiage is to be removed both from this and the push target repository.

In order to do so, I suggest that:

 1. we keep `master` for BC reasons, but as a branch-alias only (to be tested on a separate repository) 
 2. we create a new `latest` branch
 3. we change documentation to endorse installation of `roave/security-advisories:dev-latest` or such

This is currently all up in the air, since I think that `dev-master` was still somewhat special inside composer's internals (it would be allowed, even if `minimum-stability` is `stable`), but it's something we should work on long-term.

**Comment by slash3b** [comment]
I'm a bit confused about `dev-latest` part. When roave/security-advisories is updated and `latest` will be set up as default branch then `dev-latest` will be valid, right?

**Comment by Ocramius** [comment]
Handled by @slash3b in #147 - will now swap main branch :-)
