### ISSUE TITLE
Ignore and/or report invalid package names in github security advisories

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisoriesBuilder#209]
See https://github.com/Roave/SecurityAdvisories/blob/2762ddacb0bf083e0bdc53eab51361fddced402d/composer.json#L200-L201

https://github.com/advisories/GHSA-6gw4-x63h-5499 caused this to break (I had to contact the folks at @Sylius directly to get it fixed).

Basically, `sylius\sylius` was entered instead of `sylius/sylius`.

I think we can do two things:

 1. fail the build completely (good first step)
 2. ignore the packages and raise a warning (problematic, as we won't really notice it)

**Comment by slash3b** [comment]
do you think it makes sense to implement a simple validator-corrector for package name ?

**Comment by Ocramius** [comment]
Thank you, @slash3b! \o/

**Comment by Ocramius** [comment]
> do you think it makes sense to implement a simple validator-corrector for package name ?

This is already part of upstream composer tooling - I'm wondering if we should somehow notify github security about this problem in their feeds 🤔

**Comment by slash3b** [comment]
thank you, @Ocramius ^^

I did ask the one who published advisory to edit it. Waiting for a reply.

**Comment by slash3b** [comment]
It was corrected. We are good to go \o/

https://github.com/advisories/GHSA-6gw4-x63h-5499

**Comment by Ocramius** [comment]
Yup, the problem is that this will happen again 😅
