### ISSUE TITLE
Build a package to list non strict php requires

### ISSUE THREAD

**Issue by williamdes** [Roave/SecurityAdvisoriesBuilder#431]
https://twitter.com/Ocramius/status/1415064387572928514

**Comment by williamdes** [comment]
Please assign this to me, I will allocate some time to work on it

**Comment by williamdes** [comment]
Gosh, I often think about this one @Ocramius and still intend to work on it

Can you explain my how I can access the entire composer package list ?

**Comment by Ocramius** [comment]
I suggest you look at the packagist index structure 👍

**Comment by Ocramius** [comment]
Will close here: not tracking it in this project, specifically :)

**Comment by williamdes** [comment]
Sure, I really do not know why I can't get to writing code for this. I think about it quite often
That's strange
Anyway, to be continued

**Comment by williamdes** [comment]
Also I am thinking we should maybe search in the source code to know if the library did commit things to have PHP 8 support for example
Not really sure how to do this correctly

**Comment by williamdes** [comment]
3 years later and I still think about this task
A haunting ghost 😂
But I think I finally made peace with it, I have too much tasks to do already and will probably never do it

**Comment by Ocramius** [comment]
@williamdes it's fine: I have an infinite tasklist as well, and it's just the nature of our lives :-) 

From my end, I think it's more valuable to invest time in moving people to Nix derivations, than to keep banging my head against poorly designed `composer.json` files.

**Comment by williamdes** [comment]
> @williamdes it's fine: I have an infinite tasklist as well, and it's just the nature of our lives :-)

Yeah, exactly. 

> From my end, I think it's more valuable to invest time in moving people to Nix derivations, than to keep banging my head against poorly designed `composer.json` files.

Well, maybe this list will be interesting to have when PHP 9 comes to life with its breaking changes. 

If you need some help or anything around Debian/Ubuntu packaging of php tools, let me know I already maintain some of them.
