### ISSUE TITLE
Overlapping of ranges does not work fine for beta versions

### ISSUE THREAD

**Issue by stof** [Roave/SecurityAdvisoriesBuilder#7]
Looking at the diff of https://github.com/Roave/SecurityAdvisories/commit/5eb59cd740f7f76a7ad680089b6db941c645b7ba I figured out that the overlapping ranges were not properly detected when involving beta versions.

We have `"thelia/thelia": ">=2.1.0-beta1,<2.1.3|>=2.1,<2.1.2",`

As 2.1.0-beta1 is a lower version than 2.1, this is totally equivalent to the `>=2.1.0-beta1,<2.1.3` range, so the second part should have been removed.

Thus, the sorting does not seem to handle them fine either, because https://github.com/Roave/SecurityAdvisories/commit/5eb59cd740f7f76a7ad680089b6db941c645b7ba swapped the order once and https://github.com/Roave/SecurityAdvisories/commit/5eb59cd740f7f76a7ad680089b6db941c645b7ba swapped them back again (interestingly, there was another commit in the middle not swapping so it is not just swapping at each build, maybe just sorting in an unstable way)

**Comment by stof** [comment]
Looking at the testsuite, it seems like unstable releases (alpha, beta and RC) are never tested in all the logic dealing with VersionConstraint (all tests are using constraints with stable releases as bounds) so failing to handle them properly looks totally possible.

**Comment by Ocramius** [comment]
@slash3b is working on this 👍

**Comment by slash3b** [comment]
yes, I'm working on that but really slow : )
next week I'm going to have much more time

**Comment by Ocramius** [comment]
This was handled by further (exceptional) work done by @slash3b 💪
