### ISSUE TITLE
Normalize version constraints to their shortest possible form

### ISSUE THREAD

**Issue by Ocramius** [Roave/SecurityAdvisoriesBuilder#9]
This is a relatively straightforward one:

 * `>=5.0` becomes `>=5`
 * `>=5.2.0` becomes `>=5.2`

And so on.

This means that we truncate all the zeroes-only minor/patch (or further) version constraints.

**Comment by slash3b** [comment]
I think this one is tackled here https://github.com/Roave/SecurityAdvisoriesBuilder/pull/28 : )

**Comment by Ocramius** [comment]
This one is already handled in `master`, but handling of `>=5.0-alpha2` or such is still relevant as per work that was started in #28

**Comment by Ocramius** [comment]
Closing here: normalisation is already happening 👍
